# .ai_config.yml

general:
  # We want to store session files in a custom directory for this project.
  sessions_directory: "my_custom_sessions"

  auto_inject_files:
    - "PROJECT_BLUEPRINT.md"
    - "AGENTS.md"

rag:
  enable_branch_awareness: true
  oracle_cloud:
    namespace: frpowqeyehes
    bucket: bucket-20230107-0704
    region: eu-frankfurt-1
  enable_reranking: true
  # Optional: You can tune these parameters
  # retrieval_n_results: 30 # Retrieve more to start
  # rerank_top_n: 7         # Return more to the LLM


tools:
  shell:
    allowed_commands:
      - ls
      - git
      - grep
      - find
      - cat
      - echo
      - pytest
      - python