
# .ai_config.yml (Corrected Version)

general:
  # This is a good practice for project-specific session management.
  # Remember to add 'my_custom_sessions/' to your .gitignore file.
  sessions_directory: "my_custom_sessions"

  auto_inject_files:
    - "PROJECT_BLUEPRINT.md"
    - "AGENTS.md"

rag:
  # The URL of your deployed Librarian service (Corrected format).
  librarian_url: "http://138.2.183.131:8000"

  # The API key for the Librarian service.
  # This will be read from the LIBRARIAN_API_KEY environment variable.
  librarian_api_key: ${LIBRARIAN_API_KEY}

  # The number of final context chunks to request from the Librarian.
  rerank_top_n: 5

tools:
  shell:
    # A safe, curated list of allowed commands.
    # CRITICAL: 'python' and 'pytest' have been removed to prevent RCE vulnerabilities.
    allowed_commands:
      - ls
      - git
      - grep
      - find
      - cat
      - echo
