# .ai_config.yml

general:
  # This is a good practice for project-specific session management.
  # Remember to add 'my_custom_sessions/' to your .gitignore file.
  sessions_directory: "my_custom_sessions"

  auto_inject_files:
    - "PROJECT_BLUEPRINT.md"
    - "AGENTS.md"

rag:
  # Reference the LIBRARIAN_API_URL from your .env file
  librarian_url: ${LIBRARIAN_API_URL}

  # Reference the LIBRARIAN_API_KEY from your .env file
  librarian_api_key: ${LIBRARIAN_API_KEY}
  
  # The number of final context chunks to request from the Librarian.
  rerank_top_n: 5

tools:
  shell:
    # A safe, curated list of allowed commands.
    # CRITICAL: 'python' and 'pytest' have been removed to prevent RCE vulnerabilities.
    allowed_commands:
      - ls
      - git
      - grep
      - find
      - cat
      - echo
