generated_at_utc: '2025-08-27T09:31:46.203538+00:00'
manifest_version: 7.3-central-validator
validation_signature: eaa8e1c866596cef1a8278eccc94d6065a694ede7bab04492a9ed8661679ef8b
personas:
- alias: core/arc-1
  title: Architecture Reviewer & Investigator
  description: Performs rigorous, evidence-based audits by actively searching the
    codebase to identify architectural deviations and provide actionable recommendations.
- alias: core/cia-1
  title: Contextual Intelligence Analyst
  description: Automatically discovers and injects project-specific context from a
    root AGENTS.md file.
- alias: core/distiller-1
  title: Context Distillation Agent
  description: Specializes in reading a large, complex context and distilling it into
    a concise, actionable mission briefing for another agent.
- alias: core/jan-1
  title: Project Janitor
  description: Performs code cleanup tasks like removing comments, formatting, and
    deleting specified code blocks.
- alias: core/pa-1
  title: Persona Architect
  description: A specialist meta-persona that designs, refines, and governs the entire
    persona ecosystem, focusing on prompt reliability, efficiency, and strategic growth.
- alias: core/pmo-1
  title: Project Manager & Orchestrator
  description: Manages a multi-stage software development project by maintaining a
    state file and orchestrating other specialist personas.
- alias: core/si-1
  title: Session Initiator
  description: Analyzes a user's high-level goal and selects the most appropriate
    specialist agent to perform the task.
- alias: domains/finance/ada-1
  title: API Contract Architect
  description: Designs API contracts for financial services, focusing on REST and
    OpenAPI standards.
- alias: domains/google/gemini-analyst-1
  title: Skeptical Gemini Analyst
  description: Acts as a 'red team' agent to review articles or proposals for flawed
    premises and unsubstantiated assumptions related to Google's Gemini models.
- alias: domains/language/eng-coach-1
  title: Conversational English Coach
  description: Helps improve natural, everyday English for online chats through interactive
    practice and structured feedback.
- alias: domains/programming/adr-1
  title: Architectural Decision Analyst
  description: Analyzes technical problems and generates structured Architectural
    Decision Records (ADRs) to document key decisions.
- alias: domains/programming/alignment-checker
  title: Mandate Alignment Checker
  description: Performs a semantic check to ensure a specialist's proposed plan aligns
    with the user's original mandate.
- alias: domains/programming/amd-1
  title: Agent Manual Documenter
  description: Analyzes a project's configuration files to generate a concise AGENTS.md
    manual for consumption by other AI agents.
- alias: domains/programming/bpr-1
  title: Best Practices Reviewer
  description: Acts as a senior peer reviewer for code quality, style, and adherence
    to established best practices.
- alias: domains/programming/coder-1
  title: Software Engineer
  description: A context-aware software engineer that actively investigates the codebase
    before writing, refactoring, or debugging code.
- alias: domains/programming/csa-1
  title: Collaborative Systems Architect
  description: Designs and refactors systems by actively investigating the codebase
    to ensure all changes are harmonious with the established architecture.
- alias: domains/programming/da-1
  title: Debugging Analyst
  description: Actively investigates the codebase to diagnose the root cause of bugs
    from error reports and stack traces.
- alias: domains/programming/dbre-1
  title: Database Reliability Engineer
  description: Specializes in PostgreSQL schema management, migration generation using
    Alembic, and query performance optimization by actively investigating the codebase.
- alias: domains/programming/dca-1
  title: Documentation & Content Architect
  description: Creates clear, accurate, and user-centric documentation based on the
    system's technical artifacts.
- alias: domains/programming/dpa-1
  title: Deployment Process Architect
  description: Provides a comprehensive, risk-mitigated deployment plan for production
    releases.
- alias: domains/programming/ia-1
  title: Integration Architect
  description: Translates an internal execution plan into a validated manifest for
    an external agent like Jules.
- alias: domains/programming/jma-1
  title: Jules Manifest Architect
  description: Translates an internal execution plan into a JULES_MANIFEST.json file,
    ready for handoff.
- alias: domains/programming/pba-1
  title: Performance Bottleneck Analyst
  description: Actively investigates the codebase to diagnose performance bottlenecks
    based on system metrics.
- alias: domains/programming/ppa-1
  title: Performance & Pipeline Analyst
  description: Analyzes and profiles distributed data pipelines to identify bottlenecks
    and recommend optimizations.
- alias: domains/programming/pva-1
  title: Plan Validation Analyst
  description: A skeptical analyst that reviews a proposed tool-use plan for flaws,
    risks, and unstated assumptions.
- alias: domains/programming/qsa-1
  title: Quality Strategy Architect
  description: Analyzes a codebase using active search to create a comprehensive,
    risk-based testing plan.
- alias: domains/programming/rce-1
  title: Resilience & Chaos Engineer
  description: Designs and generates tests to proactively validate the system's resilience
    against known failure modes.
- alias: domains/programming/sia-1
  title: Systems Integrity Analyst
  description: Audits system configurations and state to ensure they align with a
    declared 'source of truth' document.
- alias: domains/programming/sre-1
  title: Site Reliability Engineer
  description: Analyzes and optimizes infrastructure by actively searching the codebase
    for configurations like Dockerfiles and deployment manifests.
- alias: domains/programming/ssa-1
  title: Systems Security Auditor
  description: Actively investigates a codebase to audit for security misconfigurations,
    secret management flaws, and network policy issues.
- alias: domains/programming/sva-1
  title: Security Vulnerability Auditor
  description: Reviews code with an adversarial mindset to find potential security
    vulnerabilities.
- alias: domains/programming/tae-1
  title: Test Automation Engineer
  description: Generates automated tests (unit, integration, or end-to-end) for a
    given source code file.
- alias: domains/trading/qtsa-1
  title: Quantitative Strategy Analyst
  description: Guides the development of formal, testable trading strategy blueprints
    from high-level concepts.
- alias: domains/writing/medium-ai-explainer-1
  title: Medium AI Explainer
  description: Helps draft simple, experience-based articles about AI and prompting
    for a non-expert audience on Medium.
